//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameAnarchy.Localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localize {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localize() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameAnarchy.Localization.Localize", typeof(Localize).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Add cash 的本地化字符串。
        /// </summary>
        public static string AddCash {
            get {
                return ResourceManager.GetString("AddCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add cash amount 的本地化字符串。
        /// </summary>
        public static string AddCashAmount {
            get {
                return ResourceManager.GetString("AddCashAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add cash threshold 的本地化字符串。
        /// </summary>
        public static string AddCashThreshold {
            get {
                return ResourceManager.GetString("AddCashThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Make sure Cash Anarchy feature is enabled. 的本地化字符串。
        /// </summary>
        public static string AddCashTooltip {
            get {
                return ResourceManager.GetString("AddCashTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This option allows dynamic toggle within game 的本地化字符串。
        /// </summary>
        public static string AllowsDynamicToggling {
            get {
                return ResourceManager.GetString("AllowsDynamicToggling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Amount 的本地化字符串。
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Building refund 的本地化字符串。
        /// </summary>
        public static string BuildingRefund {
            get {
                return ResourceManager.GetString("BuildingRefund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Building refund multiple factor 的本地化字符串。
        /// </summary>
        public static string BuildingRefundMultipleFactor {
            get {
                return ResourceManager.GetString("BuildingRefundMultipleFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Building spread fire probability 的本地化字符串。
        /// </summary>
        public static string BuildingSpreadFireProbability {
            get {
                return ResourceManager.GetString("BuildingSpreadFireProbability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 City Service Options 的本地化字符串。
        /// </summary>
        public static string CityServiceOptions {
            get {
                return ResourceManager.GetString("CityServiceOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Commercial 的本地化字符串。
        /// </summary>
        public static string Commercial {
            get {
                return ResourceManager.GetString("Commercial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cost 的本地化字符串。
        /// </summary>
        public static string Cost {
            get {
                return ResourceManager.GetString("Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom unlock 的本地化字符串。
        /// </summary>
        public static string CustomUnlock {
            get {
                return ResourceManager.GetString("CustomUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 These options are not available when “Unlock All” feature is enabled because Unlock All has unlocked all of the following options. 的本地化字符串。
        /// </summary>
        public static string CustomUnlockPanelTooltip {
            get {
                return ResourceManager.GetString("CustomUnlockPanelTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Achievements system is always available 的本地化字符串。
        /// </summary>
        public static string EnableAchievements {
            get {
                return ResourceManager.GetString("EnableAchievements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Info view is always available 的本地化字符串。
        /// </summary>
        public static string EnabledInfoView {
            get {
                return ResourceManager.GetString("EnabledInfoView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Skip game Intro interface 的本地化字符串。
        /// </summary>
        public static string EnabledSkipIntro {
            get {
                return ResourceManager.GetString("EnabledSkipIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Place unique buildings without limit 的本地化字符串。
        /// </summary>
        public static string EnabledUnlimitedUniqueBuildings {
            get {
                return ResourceManager.GetString("EnabledUnlimitedUniqueBuildings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fast Return 的本地化字符串。
        /// </summary>
        public static string FastReturn {
            get {
                return ResourceManager.GetString("FastReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fire Control 的本地化字符串。
        /// </summary>
        public static string FireControl {
            get {
                return ResourceManager.GetString("FireControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Free 的本地化字符串。
        /// </summary>
        public static string Free {
            get {
                return ResourceManager.GetString("Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ground pollution 的本地化字符串。
        /// </summary>
        public static string GroundPollution {
            get {
                return ResourceManager.GetString("GroundPollution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Income 的本地化字符串。
        /// </summary>
        public static string Income {
            get {
                return ResourceManager.GetString("Income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Income multiplier 的本地化字符串。
        /// </summary>
        public static string IncomeMultiplier {
            get {
                return ResourceManager.GetString("IncomeMultiplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Industrial 的本地化字符串。
        /// </summary>
        public static string Industrial {
            get {
                return ResourceManager.GetString("Industrial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Buildtin mod, Game Anarchy already includes the same functionality. Please disabled this local mod if you wan to use Game Anarchy funcitons. 的本地化字符串。
        /// </summary>
        public static string LocalModWarning {
            get {
                return ResourceManager.GetString("LocalModWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Buildtin mod, Game Anarchy already includes the same functionality. Please disable this local mod and set initial amount in GA&apos;s Settings panel in case your city goes bankrupt due to overdraft (to avoid the game crashing). 的本地化字符串。
        /// </summary>
        public static string LocalUnlimitedMoneyWarning {
            get {
                return ResourceManager.GetString("LocalUnlimitedMoneyWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Main campus building 的本地化字符串。
        /// </summary>
        public static string MainCampusBuilding {
            get {
                return ResourceManager.GetString("MainCampusBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maximize attractiveness, will atract more tourists 的本地化字符串。
        /// </summary>
        public static string MaximizeAttractiveness {
            get {
                return ResourceManager.GetString("MaximizeAttractiveness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maximize education coverage, still need schools to get educated citizens 的本地化字符串。
        /// </summary>
        public static string MaximizeEducationCoverage {
            get {
                return ResourceManager.GetString("MaximizeEducationCoverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maximize entertainment, will improve citizens&apos; happiness 的本地化字符串。
        /// </summary>
        public static string MaximizeEntertainment {
            get {
                return ResourceManager.GetString("MaximizeEntertainment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maximize fire coverage 的本地化字符串。
        /// </summary>
        public static string MaximizeFireCoverage {
            get {
                return ResourceManager.GetString("MaximizeFireCoverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maximize the land value of city 的本地化字符串。
        /// </summary>
        public static string MaximizeLandValue {
            get {
                return ResourceManager.GetString("MaximizeLandValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Big City 的本地化字符串。
        /// </summary>
        public static string MilestonelevelName_BigCity {
            get {
                return ResourceManager.GetString("MilestonelevelName_BigCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Big Town 的本地化字符串。
        /// </summary>
        public static string MilestonelevelName_BigTown {
            get {
                return ResourceManager.GetString("MilestonelevelName_BigTown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Boom Town 的本地化字符串。
        /// </summary>
        public static string MilestonelevelName_BoomTown {
            get {
                return ResourceManager.GetString("MilestonelevelName_BoomTown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Busy Town 的本地化字符串。
        /// </summary>
        public static string MilestonelevelName_BusyTown {
            get {
                return ResourceManager.GetString("MilestonelevelName_BusyTown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Capital City 的本地化字符串。
        /// </summary>
        public static string MilestonelevelName_CapitalCity {
            get {
                return ResourceManager.GetString("MilestonelevelName_CapitalCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Colossal City 的本地化字符串。
        /// </summary>
        public static string MilestonelevelName_ColossalCity {
            get {
                return ResourceManager.GetString("MilestonelevelName_ColossalCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Grand City 的本地化字符串。
        /// </summary>
        public static string MilestonelevelName_GrandCity {
            get {
                return ResourceManager.GetString("MilestonelevelName_GrandCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Little Hamlet 的本地化字符串。
        /// </summary>
        public static string MilestonelevelName_LittleHamlet {
            get {
                return ResourceManager.GetString("MilestonelevelName_LittleHamlet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Megalopolis 的本地化字符串。
        /// </summary>
        public static string MilestonelevelName_Megalopolis {
            get {
                return ResourceManager.GetString("MilestonelevelName_Megalopolis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Metropolis 的本地化字符串。
        /// </summary>
        public static string MilestonelevelName_Metropolis {
            get {
                return ResourceManager.GetString("MilestonelevelName_Metropolis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Milestone unlock level 的本地化字符串。
        /// </summary>
        public static string MilestonelevelName_MilestoneUnlockLevel {
            get {
                return ResourceManager.GetString("MilestonelevelName_MilestoneUnlockLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Small City 的本地化字符串。
        /// </summary>
        public static string MilestonelevelName_SmallCity {
            get {
                return ResourceManager.GetString("MilestonelevelName_SmallCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tiny Town 的本地化字符串。
        /// </summary>
        public static string MilestonelevelName_TinyTown {
            get {
                return ResourceManager.GetString("MilestonelevelName_TinyTown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vanilla 的本地化字符串。
        /// </summary>
        public static string MilestonelevelName_Vanilla {
            get {
                return ResourceManager.GetString("MilestonelevelName_Vanilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Worthy Village 的本地化字符串。
        /// </summary>
        public static string MilestonelevelName_WorthyVillage {
            get {
                return ResourceManager.GetString("MilestonelevelName_WorthyVillage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extends and optimize game&apos;s functions. 的本地化字符串。
        /// </summary>
        public static string MOD_Description {
            get {
                return ResourceManager.GetString("MOD_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Money anarchy mode 的本地化字符串。
        /// </summary>
        public static string MoneyAnarchyMode {
            get {
                return ResourceManager.GetString("MoneyAnarchyMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This option allows automatic (set the following 2 options)/manual (use hotkey) set money, allows dynamic toggle within game 的本地化字符串。
        /// </summary>
        public static string MoneyAnarchyModeMinor {
            get {
                return ResourceManager.GetString("MoneyAnarchyModeMinor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Monument 的本地化字符串。
        /// </summary>
        public static string Monument {
            get {
                return ResourceManager.GetString("Monument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Noise pollution 的本地化字符串。
        /// </summary>
        public static string NoisePollution {
            get {
                return ResourceManager.GetString("NoisePollution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Non-spread of fire 的本地化字符串。
        /// </summary>
        public static string NoSpreadFire {
            get {
                return ResourceManager.GetString("NoSpreadFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Office 的本地化字符串。
        /// </summary>
        public static string Office {
            get {
                return ResourceManager.GetString("Office", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Oil depletion rate 的本地化字符串。
        /// </summary>
        public static string OilDepletionRate {
            get {
                return ResourceManager.GetString("OilDepletionRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Control Panel 的本地化字符串。
        /// </summary>
        public static string OpenControlPanel {
            get {
                return ResourceManager.GetString("OpenControlPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Optimize Options 的本地化字符串。
        /// </summary>
        public static string OptimizeOptions {
            get {
                return ResourceManager.GetString("OptimizeOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This option takes effect after adjustment 的本地化字符串。
        /// </summary>
        public static string OptionPanelCategoriesHorizontalOffsetMinor {
            get {
                return ResourceManager.GetString("OptionPanelCategoriesHorizontalOffsetMinor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show mod updated date in options panel categories 的本地化字符串。
        /// </summary>
        public static string OptionPanelCategoriesUpdated {
            get {
                return ResourceManager.GetString("OptionPanelCategoriesUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This option only takes effect after refreshing the plugins list or restarting the game 的本地化字符串。
        /// </summary>
        public static string OptionPanelCategoriesUpdatedMinor {
            get {
                return ResourceManager.GetString("OptionPanelCategoriesUpdatedMinor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Options panel categories bar horizontal offset 的本地化字符串。
        /// </summary>
        public static string OptionsPanelHorizontalOffset {
            get {
                return ResourceManager.GetString("OptionsPanelHorizontalOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Options panel categories bar horizontal offset will take effect after the options panel is reopened 的本地化字符串。
        /// </summary>
        public static string OptionsPanelHorizontalOffsetTooltip {
            get {
                return ResourceManager.GetString("OptionsPanelHorizontalOffsetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ore depletion rate 的本地化字符串。
        /// </summary>
        public static string OreDepletionRate {
            get {
                return ResourceManager.GetString("OreDepletionRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Other functions 的本地化字符串。
        /// </summary>
        public static string OtherFunctionsMajor {
            get {
                return ResourceManager.GetString("OtherFunctionsMajor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use the shortcut keys or the UUI button to invoke the Control Panel, if you want to adjust the options in the Control Panel, close the Options Panel first. 的本地化字符串。
        /// </summary>
        public static string OtherFunctionsMinor {
            get {
                return ResourceManager.GetString("OtherFunctionsMinor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Player building 的本地化字符串。
        /// </summary>
        public static string PlayerBuilding {
            get {
                return ResourceManager.GetString("PlayerBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bulldozing refund 的本地化字符串。
        /// </summary>
        public static string Refund {
            get {
                return ResourceManager.GetString("Refund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Relocate building 的本地化字符串。
        /// </summary>
        public static string RelocateBuilding {
            get {
                return ResourceManager.GetString("RelocateBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Construction cost * Multiplier factor = Cost 的本地化字符串。
        /// </summary>
        public static string RelocateBuildingMinor {
            get {
                return ResourceManager.GetString("RelocateBuildingMinor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove airport building fire 的本地化字符串。
        /// </summary>
        public static string RemoveAirportBuildingFire {
            get {
                return ResourceManager.GetString("RemoveAirportBuildingFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove building refund time limitation 的本地化字符串。
        /// </summary>
        public static string RemoveBuildingRefundTimeLimitation {
            get {
                return ResourceManager.GetString("RemoveBuildingRefundTimeLimitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove campus building fire 的本地化字符串。
        /// </summary>
        public static string RemoveCampusBuildingFire {
            get {
                return ResourceManager.GetString("RemoveCampusBuildingFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove commercial building fire 的本地化字符串。
        /// </summary>
        public static string RemoveCommercialBuildingFire {
            get {
                return ResourceManager.GetString("RemoveCommercialBuildingFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove criminals from all buildings and maximize police service coverage 的本地化字符串。
        /// </summary>
        public static string RemoveCrime {
            get {
                return ResourceManager.GetString("RemoveCrime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove dead citizens and maximize death care coverage 的本地化字符串。
        /// </summary>
        public static string RemoveDeath {
            get {
                return ResourceManager.GetString("RemoveDeath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove garbage 的本地化字符串。
        /// </summary>
        public static string RemoveGarbage {
            get {
                return ResourceManager.GetString("RemoveGarbage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove industrial building fire 的本地化字符串。
        /// </summary>
        public static string RemoveIndustrialBuildingFire {
            get {
                return ResourceManager.GetString("RemoveIndustrialBuildingFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove museum fire 的本地化字符串。
        /// </summary>
        public static string RemoveMuseumFire {
            get {
                return ResourceManager.GetString("RemoveMuseumFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove office building fire 的本地化字符串。
        /// </summary>
        public static string RemoveOfficeBuildingFire {
            get {
                return ResourceManager.GetString("RemoveOfficeBuildingFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove park building fire 的本地化字符串。
        /// </summary>
        public static string RemoveParkBuildingFire {
            get {
                return ResourceManager.GetString("RemoveParkBuildingFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove player building fire 的本地化字符串。
        /// </summary>
        public static string RemovePlayerBuildingFire {
            get {
                return ResourceManager.GetString("RemovePlayerBuildingFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove pollution 的本地化字符串。
        /// </summary>
        public static string RemovePollution {
            get {
                return ResourceManager.GetString("RemovePollution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove residential building fire 的本地化字符串。
        /// </summary>
        public static string RemoveResidentialBuildingFire {
            get {
                return ResourceManager.GetString("RemoveResidentialBuildingFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove Segment refund time limitation 的本地化字符串。
        /// </summary>
        public static string RemoveSegmentRefundTimeLimitation {
            get {
                return ResourceManager.GetString("RemoveSegmentRefundTimeLimitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Residential 的本地化字符串。
        /// </summary>
        public static string Residential {
            get {
                return ResourceManager.GetString("Residential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resource Options 的本地化字符串。
        /// </summary>
        public static string ResourceOptions {
            get {
                return ResourceManager.GetString("ResourceOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Segment refund 的本地化字符串。
        /// </summary>
        public static string SegmentRefund {
            get {
                return ResourceManager.GetString("SegmentRefund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Segment refund multiple factor 的本地化字符串。
        /// </summary>
        public static string SegmentRefundMultipleFactor {
            get {
                return ResourceManager.GetString("SegmentRefundMultipleFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Service 的本地化字符串。
        /// </summary>
        public static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sort mods names in options panel 的本地化字符串。
        /// </summary>
        public static string SortSettings {
            get {
                return ResourceManager.GetString("SortSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Space radar 的本地化字符串。
        /// </summary>
        public static string SpaceRadar {
            get {
                return ResourceManager.GetString("SpaceRadar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game start money 的本地化字符串。
        /// </summary>
        public static string StartMoneyMajor {
            get {
                return ResourceManager.GetString("StartMoneyMajor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set value before you start gaming. If you don&apos;t want money to be this value every time you load save, disable this feature after enabling it once, if you load save, the money will change after the game simulation starts. 的本地化字符串。
        /// </summary>
        public static string StartMoneyMinor {
            get {
                return ResourceManager.GetString("StartMoneyMinor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stock exchange 的本地化字符串。
        /// </summary>
        public static string StockExchange {
            get {
                return ResourceManager.GetString("StockExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tree spread fire probability 的本地化字符串。
        /// </summary>
        public static string TreeSpreadFireProbability {
            get {
                return ResourceManager.GetString("TreeSpreadFireProbability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unique factory 的本地化字符串。
        /// </summary>
        public static string UniqueFactory {
            get {
                return ResourceManager.GetString("UniqueFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unique faculty 的本地化字符串。
        /// </summary>
        public static string UniqueFaculty {
            get {
                return ResourceManager.GetString("UniqueFaculty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unlimited 的本地化字符串。
        /// </summary>
        public static string Unlimited {
            get {
                return ResourceManager.GetString("Unlimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unlock all 的本地化字符串。
        /// </summary>
        public static string UnlockAll {
            get {
                return ResourceManager.GetString("UnlockAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 It is recommended to set this before you start the game. If disabled this option still unlocks something, make sure you have disabled Find It! &quot;Unlock All&quot; option. The &quot;Unlock all&quot; option in Find It! only unlocks all assets in the Find it! menu, but do not unlock milestones. 的本地化字符串。
        /// </summary>
        public static string UnlockAllMinor {
            get {
                return ResourceManager.GetString("UnlockAllMinor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unlock all roads 的本地化字符串。
        /// </summary>
        public static string UnlockAllRoads {
            get {
                return ResourceManager.GetString("UnlockAllRoads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unlock metro track 的本地化字符串。
        /// </summary>
        public static string UnlockMetroTrack {
            get {
                return ResourceManager.GetString("UnlockMetroTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unlock Options 的本地化字符串。
        /// </summary>
        public static string UnlockOptions {
            get {
                return ResourceManager.GetString("UnlockOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unlock policies panel 的本地化字符串。
        /// </summary>
        public static string UnlockPolicies {
            get {
                return ResourceManager.GetString("UnlockPolicies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unlock train track 的本地化字符串。
        /// </summary>
        public static string UnlockTrainTrack {
            get {
                return ResourceManager.GetString("UnlockTrainTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unlock all transports 的本地化字符串。
        /// </summary>
        public static string UnlockTransport {
            get {
                return ResourceManager.GetString("UnlockTransport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unlock unique Building 的本地化字符串。
        /// </summary>
        public static string UnlockUniqueBuilding {
            get {
                return ResourceManager.GetString("UnlockUniqueBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unlock all unique buildings at levels 1 through 6. Due to game restrictions, if this option is forced to be unlocked, a small number of buildings will be unlocked, but not all. 的本地化字符串。
        /// </summary>
        public static string UnlockUniqueBuildingMinor {
            get {
                return ResourceManager.GetString("UnlockUniqueBuildingMinor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} days ago 的本地化字符串。
        /// </summary>
        public static string Updated_DaysAgo {
            get {
                return ResourceManager.GetString("Updated_DaysAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last year 的本地化字符串。
        /// </summary>
        public static string Updated_LastYear {
            get {
                return ResourceManager.GetString("Updated_LastYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} month ago 的本地化字符串。
        /// </summary>
        public static string Updated_MonthAgo {
            get {
                return ResourceManager.GetString("Updated_MonthAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} months ago 的本地化字符串。
        /// </summary>
        public static string Updated_MonthsAgo {
            get {
                return ResourceManager.GetString("Updated_MonthsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Today at {0:HH:mm} 的本地化字符串。
        /// </summary>
        public static string Updated_Today {
            get {
                return ResourceManager.GetString("Updated_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} years ago 的本地化字符串。
        /// </summary>
        public static string Updated_YearsAgo {
            get {
                return ResourceManager.GetString("Updated_YearsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yesterday 的本地化字符串。
        /// </summary>
        public static string Updated_Yesterday {
            get {
                return ResourceManager.GetString("Updated_Yesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yesterday at {0:HH:mm} 的本地化字符串。
        /// </summary>
        public static string Updated_YesterdayAt {
            get {
                return ResourceManager.GetString("Updated_YesterdayAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ADD]New control panel, use default hotkey Ctrl+Shift+G or use UUI panel to invoke new control panel. 的本地化字符串。
        /// </summary>
        public static string UpdateLog_V0_9_7ADD1 {
            get {
                return ResourceManager.GetString("UpdateLog_V0_9_7ADD1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ADD]Place unique buildings without limit features now split and integrated into control panel. 的本地化字符串。
        /// </summary>
        public static string UpdateLog_V0_9_7ADD2 {
            get {
                return ResourceManager.GetString("UpdateLog_V0_9_7ADD2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ADD]Added fire spread control function. 的本地化字符串。
        /// </summary>
        public static string UpdateLog_V0_9_7ADD3 {
            get {
                return ResourceManager.GetString("UpdateLog_V0_9_7ADD3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ADD]Remove fire function now split into multiple options, can control fire of different building types. 的本地化字符串。
        /// </summary>
        public static string UpdateLog_V0_9_7ADD4 {
            get {
                return ResourceManager.GetString("UpdateLog_V0_9_7ADD4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ADD]Added Turkish localization. 的本地化字符串。
        /// </summary>
        public static string UpdateLog_V0_9_7ADD5 {
            get {
                return ResourceManager.GetString("UpdateLog_V0_9_7ADD5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [FIX]Fixed abnormal UI component location. 的本地化字符串。
        /// </summary>
        public static string UpdateLog_V0_9_7FIX {
            get {
                return ResourceManager.GetString("UpdateLog_V0_9_7FIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [UPT]Updated framework, performance improvement. 的本地化字符串。
        /// </summary>
        public static string UpdateLog_V0_9_7UPT1 {
            get {
                return ResourceManager.GetString("UpdateLog_V0_9_7UPT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [UPT]Updated Option Panel UI components. 的本地化字符串。
        /// </summary>
        public static string UpdateLog_V0_9_7UPT2 {
            get {
                return ResourceManager.GetString("UpdateLog_V0_9_7UPT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ADD]Added advanced option for reset mod config. 的本地化字符串。
        /// </summary>
        public static string UpdateLog_V0_9_8ADD {
            get {
                return ResourceManager.GetString("UpdateLog_V0_9_8ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [FIX]Fixed an issue where control panel did not follow the language toggle. 的本地化字符串。
        /// </summary>
        public static string UpdateLog_V0_9_8FIX1 {
            get {
                return ResourceManager.GetString("UpdateLog_V0_9_8FIX1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [FIX]Fixed an issue where the money option in options panel could not be changed. 的本地化字符串。
        /// </summary>
        public static string UpdateLog_V0_9_8FIX2 {
            get {
                return ResourceManager.GetString("UpdateLog_V0_9_8FIX2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [OPT]Optimized control panel invoke speed. 的本地化字符串。
        /// </summary>
        public static string UpdateLog_V0_9_8OPT1 {
            get {
                return ResourceManager.GetString("UpdateLog_V0_9_8OPT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [OPT]Optimized control panel toggle button UI style. 的本地化字符串。
        /// </summary>
        public static string UpdateLog_V0_9_8OPT2 {
            get {
                return ResourceManager.GetString("UpdateLog_V0_9_8OPT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [UPT]Updated compatibility check. 的本地化字符串。
        /// </summary>
        public static string UpdateLog_V0_9_8UPT {
            get {
                return ResourceManager.GetString("UpdateLog_V0_9_8UPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Added show mods updated date for the category bar of the options panel function. 的本地化字符串。
        /// </summary>
        public static string UpdateLog_V0_9_9ADD0 {
            get {
                return ResourceManager.GetString("UpdateLog_V0_9_9ADD0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Added building, segment refund function, including remove time limitation, multiplier factor adjustment, included in the control panel. 的本地化字符串。
        /// </summary>
        public static string UpdateLog_V0_9_9ADD1 {
            get {
                return ResourceManager.GetString("UpdateLog_V0_9_9ADD1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Option panel added a entry button option to invoke the control panel. 的本地化字符串。
        /// </summary>
        public static string UpdateLog_V0_9_9ADD2 {
            get {
                return ResourceManager.GetString("UpdateLog_V0_9_9ADD2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Added the ability to adjust the cost of relocate building, included in the control panel. 的本地化字符串。
        /// </summary>
        public static string UpdateLog_V0_9_9ADD3 {
            get {
                return ResourceManager.GetString("UpdateLog_V0_9_9ADD3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fixed an issue where still catch fire after remove fires. 的本地化字符串。
        /// </summary>
        public static string UpdateLog_V0_9_9FIX0 {
            get {
                return ResourceManager.GetString("UpdateLog_V0_9_9FIX0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Optimized the options panel categories horizontal offset option, which now takes effect after adjustment. 的本地化字符串。
        /// </summary>
        public static string UpdateLog_V0_9_9OPT0 {
            get {
                return ResourceManager.GetString("UpdateLog_V0_9_9OPT0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Optimized the start money setting logic so that the start money is the value you set when you start a new game. 的本地化字符串。
        /// </summary>
        public static string UpdateLog_V0_9_9OPT1 {
            get {
                return ResourceManager.GetString("UpdateLog_V0_9_9OPT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Added Slovak localization. 的本地化字符串。
        /// </summary>
        public static string UpdateLog_V0_9_9TRAN {
            get {
                return ResourceManager.GetString("UpdateLog_V0_9_9TRAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Updated UI style. 的本地化字符串。
        /// </summary>
        public static string UpdateLog_V0_9_9UPT {
            get {
                return ResourceManager.GetString("UpdateLog_V0_9_9UPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vanilla 的本地化字符串。
        /// </summary>
        public static string Vanilla {
            get {
                return ResourceManager.GetString("Vanilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vanilla unlimited money mode 的本地化字符串。
        /// </summary>
        public static string VanillaUnlimitedMoneyMode {
            get {
                return ResourceManager.GetString("VanillaUnlimitedMoneyMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Money in game only displays “∞”, this option allows dynamic toggle within game 的本地化字符串。
        /// </summary>
        public static string VanillaUnlimitedMoneyModeMinor {
            get {
                return ResourceManager.GetString("VanillaUnlimitedMoneyModeMinor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Water pollution 的本地化字符串。
        /// </summary>
        public static string WaterPollution {
            get {
                return ResourceManager.GetString("WaterPollution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Weather radar 的本地化字符串。
        /// </summary>
        public static string WeatherRadar {
            get {
                return ResourceManager.GetString("WeatherRadar", resourceCulture);
            }
        }
    }
}
