//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameAnarchy {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localize {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localize() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameAnarchy.Localization.Localize", typeof(Localize).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Add cash 的本地化字符串。
        /// </summary>
        public static string AddCash {
            get {
                return ResourceManager.GetString("AddCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add cash amount 的本地化字符串。
        /// </summary>
        public static string AddCashAmount {
            get {
                return ResourceManager.GetString("AddCashAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add cash threshold 的本地化字符串。
        /// </summary>
        public static string AddCashThreshold {
            get {
                return ResourceManager.GetString("AddCashThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Make sure Cash Anarchy feature is enabled. 的本地化字符串。
        /// </summary>
        public static string AddCashTooltip {
            get {
                return ResourceManager.GetString("AddCashTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cash anarchy mode, automatic/manual(hotkey) add cash 的本地化字符串。
        /// </summary>
        public static string CashAnarchy {
            get {
                return ResourceManager.GetString("CashAnarchy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 City Service Options 的本地化字符串。
        /// </summary>
        public static string CityServiceOptions {
            get {
                return ResourceManager.GetString("CityServiceOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Commercial income multiplier factor 的本地化字符串。
        /// </summary>
        public static string CommercialMultiplierFactor {
            get {
                return ResourceManager.GetString("CommercialMultiplierFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom unlock 的本地化字符串。
        /// </summary>
        public static string CustomUnlock {
            get {
                return ResourceManager.GetString("CustomUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 These options are not available when “Unlock All” feature is enabled because Unlock All has unlocked all of the following options. 的本地化字符串。
        /// </summary>
        public static string CustomUnlockPanelTooltip {
            get {
                return ResourceManager.GetString("CustomUnlockPanelTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0 indicates unlimited oil/ore resources, and 100 indicates vanilla depletion rate. 的本地化字符串。
        /// </summary>
        public static string DepletionRateTooltip {
            get {
                return ResourceManager.GetString("DepletionRateTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Achievements system is always available 的本地化字符串。
        /// </summary>
        public static string EnableAchievements {
            get {
                return ResourceManager.GetString("EnableAchievements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Info view is always available 的本地化字符串。
        /// </summary>
        public static string EnabledInfoView {
            get {
                return ResourceManager.GetString("EnabledInfoView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Skip game Intro interface 的本地化字符串。
        /// </summary>
        public static string EnabledSkipIntro {
            get {
                return ResourceManager.GetString("EnabledSkipIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Allow place unique buildings without limit 的本地化字符串。
        /// </summary>
        public static string EnabledUnlimitedUniqueBuildings {
            get {
                return ResourceManager.GetString("EnabledUnlimitedUniqueBuildings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fast Return 的本地化字符串。
        /// </summary>
        public static string FastReturn {
            get {
                return ResourceManager.GetString("FastReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Income Options 的本地化字符串。
        /// </summary>
        public static string IncomeOptions {
            get {
                return ResourceManager.GetString("IncomeOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Industrial income multiplier factor 的本地化字符串。
        /// </summary>
        public static string IndustrialMultiplierFactor {
            get {
                return ResourceManager.GetString("IndustrialMultiplierFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game Initial cash 的本地化字符串。
        /// </summary>
        public static string InitialCash {
            get {
                return ResourceManager.GetString("InitialCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set value before you start gaming. If you don&apos;t want money to be this value every time you load save, disable this feature after enabling it once. Cash will change after game simulation starts. 的本地化字符串。
        /// </summary>
        public static string InitialCashWarning {
            get {
                return ResourceManager.GetString("InitialCashWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Buildtin mod, Game Anarchy already includes the same functionality. Please disabled this local mod if you wan to use Game Anarchy funcitons. 的本地化字符串。
        /// </summary>
        public static string LocalModWarning {
            get {
                return ResourceManager.GetString("LocalModWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Buildtin mod, Game Anarchy already includes the same functionality. Please disable this local mod and set initial amount in GA&apos;s Settings panel in case your city goes bankrupt due to overdraft (to avoid the game crashing). 的本地化字符串。
        /// </summary>
        public static string LocalUnlimitedMoneyWarning {
            get {
                return ResourceManager.GetString("LocalUnlimitedMoneyWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maximize attractiveness, will atract more tourists 的本地化字符串。
        /// </summary>
        public static string MaximizeAttractiveness {
            get {
                return ResourceManager.GetString("MaximizeAttractiveness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maximize education coverage, still need schools to get educated citizens 的本地化字符串。
        /// </summary>
        public static string MaximizeEducationCoverage {
            get {
                return ResourceManager.GetString("MaximizeEducationCoverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maximize entertainment, will improve citizens&apos; happiness 的本地化字符串。
        /// </summary>
        public static string MaximizeEntertainment {
            get {
                return ResourceManager.GetString("MaximizeEntertainment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maximize the land value of city 的本地化字符串。
        /// </summary>
        public static string MaximizeLandValue {
            get {
                return ResourceManager.GetString("MaximizeLandValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Big City 的本地化字符串。
        /// </summary>
        public static string MilestonelevelName_BigCity {
            get {
                return ResourceManager.GetString("MilestonelevelName_BigCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Big Town 的本地化字符串。
        /// </summary>
        public static string MilestonelevelName_BigTown {
            get {
                return ResourceManager.GetString("MilestonelevelName_BigTown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Boom Town 的本地化字符串。
        /// </summary>
        public static string MilestonelevelName_BoomTown {
            get {
                return ResourceManager.GetString("MilestonelevelName_BoomTown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Busy Town 的本地化字符串。
        /// </summary>
        public static string MilestonelevelName_BusyTown {
            get {
                return ResourceManager.GetString("MilestonelevelName_BusyTown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Capital City 的本地化字符串。
        /// </summary>
        public static string MilestonelevelName_CapitalCity {
            get {
                return ResourceManager.GetString("MilestonelevelName_CapitalCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Colossal City 的本地化字符串。
        /// </summary>
        public static string MilestonelevelName_ColossalCity {
            get {
                return ResourceManager.GetString("MilestonelevelName_ColossalCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Grand City 的本地化字符串。
        /// </summary>
        public static string MilestonelevelName_GrandCity {
            get {
                return ResourceManager.GetString("MilestonelevelName_GrandCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Little Hamlet 的本地化字符串。
        /// </summary>
        public static string MilestonelevelName_LittleHamlet {
            get {
                return ResourceManager.GetString("MilestonelevelName_LittleHamlet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Megalopolis 的本地化字符串。
        /// </summary>
        public static string MilestonelevelName_Megalopolis {
            get {
                return ResourceManager.GetString("MilestonelevelName_Megalopolis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Metropolis 的本地化字符串。
        /// </summary>
        public static string MilestonelevelName_Metropolis {
            get {
                return ResourceManager.GetString("MilestonelevelName_Metropolis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Milestone unlock level 的本地化字符串。
        /// </summary>
        public static string MilestonelevelName_MilestoneUnlockLevel {
            get {
                return ResourceManager.GetString("MilestonelevelName_MilestoneUnlockLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Small City 的本地化字符串。
        /// </summary>
        public static string MilestonelevelName_SmallCity {
            get {
                return ResourceManager.GetString("MilestonelevelName_SmallCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tiny Town 的本地化字符串。
        /// </summary>
        public static string MilestonelevelName_TinyTown {
            get {
                return ResourceManager.GetString("MilestonelevelName_TinyTown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vanilla 的本地化字符串。
        /// </summary>
        public static string MilestonelevelName_Vanilla {
            get {
                return ResourceManager.GetString("MilestonelevelName_Vanilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Worthy Village 的本地化字符串。
        /// </summary>
        public static string MilestonelevelName_WorthyVillage {
            get {
                return ResourceManager.GetString("MilestonelevelName_WorthyVillage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extends and optimize game&apos;s functions. 的本地化字符串。
        /// </summary>
        public static string MOD_Description {
            get {
                return ResourceManager.GetString("MOD_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Office income multiplier factor 的本地化字符串。
        /// </summary>
        public static string OfficeMultiplierFactor {
            get {
                return ResourceManager.GetString("OfficeMultiplierFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Oil depletion rate 的本地化字符串。
        /// </summary>
        public static string OilDepletionRate {
            get {
                return ResourceManager.GetString("OilDepletionRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Optimize Options 的本地化字符串。
        /// </summary>
        public static string OptimizeOptions {
            get {
                return ResourceManager.GetString("OptimizeOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Options panel categories bar horizontal offset 的本地化字符串。
        /// </summary>
        public static string OptionsPanelHorizontalOffset {
            get {
                return ResourceManager.GetString("OptionsPanelHorizontalOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Options panel categories bar horizontal offset will take effect after the options panel is reopened. 的本地化字符串。
        /// </summary>
        public static string OptionsPanelHorizontalOffsetTooltip {
            get {
                return ResourceManager.GetString("OptionsPanelHorizontalOffsetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ore depletion rate 的本地化字符串。
        /// </summary>
        public static string OreDepletionRate {
            get {
                return ResourceManager.GetString("OreDepletionRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bulldozing building full refund 的本地化字符串。
        /// </summary>
        public static string Refund {
            get {
                return ResourceManager.GetString("Refund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove criminals from all buildings and maximize police service coverage 的本地化字符串。
        /// </summary>
        public static string RemoveCrime {
            get {
                return ResourceManager.GetString("RemoveCrime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove dead citizens and maximize death care coverage 的本地化字符串。
        /// </summary>
        public static string RemoveDeath {
            get {
                return ResourceManager.GetString("RemoveDeath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove fire hazards and maximize fire coverage 的本地化字符串。
        /// </summary>
        public static string RemoveFire {
            get {
                return ResourceManager.GetString("RemoveFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove garbage 的本地化字符串。
        /// </summary>
        public static string RemoveGarbage {
            get {
                return ResourceManager.GetString("RemoveGarbage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove the source of ground pollution 的本地化字符串。
        /// </summary>
        public static string RemoveGroundPollution {
            get {
                return ResourceManager.GetString("RemoveGroundPollution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove the source of noise pollution 的本地化字符串。
        /// </summary>
        public static string RemoveNoisePollution {
            get {
                return ResourceManager.GetString("RemoveNoisePollution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove the source of water pollution 的本地化字符串。
        /// </summary>
        public static string RemoveWaterPollution {
            get {
                return ResourceManager.GetString("RemoveWaterPollution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset value 的本地化字符串。
        /// </summary>
        public static string ResetValue {
            get {
                return ResourceManager.GetString("ResetValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Residential income multiplier factor 的本地化字符串。
        /// </summary>
        public static string ResidentialMultiplierFactor {
            get {
                return ResourceManager.GetString("ResidentialMultiplierFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resource Options 的本地化字符串。
        /// </summary>
        public static string ResourceOptions {
            get {
                return ResourceManager.GetString("ResourceOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sort mods names in options panel 的本地化字符串。
        /// </summary>
        public static string SortSettings {
            get {
                return ResourceManager.GetString("SortSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unlock all 的本地化字符串。
        /// </summary>
        public static string UnlockAll {
            get {
                return ResourceManager.GetString("UnlockAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unlock all roads 的本地化字符串。
        /// </summary>
        public static string UnlockAllRoads {
            get {
                return ResourceManager.GetString("UnlockAllRoads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unlock metro track 的本地化字符串。
        /// </summary>
        public static string UnlockMetroTrack {
            get {
                return ResourceManager.GetString("UnlockMetroTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unlock Options 的本地化字符串。
        /// </summary>
        public static string UnlockOptions {
            get {
                return ResourceManager.GetString("UnlockOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unlock policies panel 的本地化字符串。
        /// </summary>
        public static string UnlockPolicies {
            get {
                return ResourceManager.GetString("UnlockPolicies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unlock train track 的本地化字符串。
        /// </summary>
        public static string UnlockTrainTrack {
            get {
                return ResourceManager.GetString("UnlockTrainTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unlock all transports 的本地化字符串。
        /// </summary>
        public static string UnlockTransport {
            get {
                return ResourceManager.GetString("UnlockTransport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ADD]Add initial cash function. 的本地化字符串。
        /// </summary>
        public static string UpdateLog_V0_9_0_ADD1 {
            get {
                return ResourceManager.GetString("UpdateLog_V0_9_0_ADD1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ADD]Add option panel categories bar horizontal offset adjustment function. 的本地化字符串。
        /// </summary>
        public static string UpdateLog_V0_9_0_ADD2 {
            get {
                return ResourceManager.GetString("UpdateLog_V0_9_0_ADD2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ADD]Add original Unlimited Money function, can be dynamically toggle. 的本地化字符串。
        /// </summary>
        public static string UpdateLog_V0_9_0_ADD3 {
            get {
                return ResourceManager.GetString("UpdateLog_V0_9_0_ADD3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ADD]Add Info View available function. 的本地化字符串。
        /// </summary>
        public static string UpdateLog_V0_9_0_ADD4 {
            get {
                return ResourceManager.GetString("UpdateLog_V0_9_0_ADD4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [FIX]Achievements button now works properly. 的本地化字符串。
        /// </summary>
        public static string UpdateLog_V0_9_0_FIX1 {
            get {
                return ResourceManager.GetString("UpdateLog_V0_9_0_FIX1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [UPT]Options panel was completely rewritten to support better extensions. 的本地化字符串。
        /// </summary>
        public static string UpdateLog_V0_9_0_UPT1 {
            get {
                return ResourceManager.GetString("UpdateLog_V0_9_0_UPT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [UPT]Updated compatibility check function. 的本地化字符串。
        /// </summary>
        public static string UpdateLog_V0_9_0_UPT2 {
            get {
                return ResourceManager.GetString("UpdateLog_V0_9_0_UPT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [UPT]Updated multi-language support framework. 的本地化字符串。
        /// </summary>
        public static string UpdateLog_V0_9_0_UPT3 {
            get {
                return ResourceManager.GetString("UpdateLog_V0_9_0_UPT3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ADD]Add custom unlock function, includes custom milestones level, all roads, policy panel, transport. 的本地化字符串。
        /// </summary>
        public static string UpdateLog_V0_9_1_ADD1 {
            get {
                return ResourceManager.GetString("UpdateLog_V0_9_1_ADD1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ADJ]Adjust Oil/Ore function, now can adjust depletion rate, this version update will reset this function, please go to the options panel to reset oil/ore depletion rate. 的本地化字符串。
        /// </summary>
        public static string UpdateLog_V0_9_1_ADJ1 {
            get {
                return ResourceManager.GetString("UpdateLog_V0_9_1_ADJ1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [OPT]Optimize language switching speed and language list format. 的本地化字符串。
        /// </summary>
        public static string UpdateLog_V0_9_1_OPT1 {
            get {
                return ResourceManager.GetString("UpdateLog_V0_9_1_OPT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vanilla unlimited money mode, allow dynamic toggling 的本地化字符串。
        /// </summary>
        public static string VanillaUnlimitedMoney {
            get {
                return ResourceManager.GetString("VanillaUnlimitedMoney", resourceCulture);
            }
        }
    }
}
