//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MbyronModsCommon {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonLocalize {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonLocalize() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameAnarchy.CommonLocalize", typeof(CommonLocalize).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Change log 的本地化字符串。
        /// </summary>
        public static string ChangeLog {
            get {
                return ResourceManager.GetString("ChangeLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mod change log 的本地化字符串。
        /// </summary>
        public static string ChangeLog_Major {
            get {
                return ResourceManager.GetString("ChangeLog_Major", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check 的本地化字符串。
        /// </summary>
        public static string Check {
            get {
                return ResourceManager.GetString("Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This mod is incompatible. 的本地化字符串。
        /// </summary>
        public static string CompatibilityCheck_Incompatible {
            get {
                return ResourceManager.GetString("CompatibilityCheck_Incompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mod compatibility check 的本地化字符串。
        /// </summary>
        public static string CompatibilityCheck_Major {
            get {
                return ResourceManager.GetString("CompatibilityCheck_Major", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This function only detects compatibility issues related to this mod. To check compatibility for all mods, [Compatibility Report] mod is recommended. 的本地化字符串。
        /// </summary>
        public static string CompatibilityCheck_Minor {
            get {
                return ResourceManager.GetString("CompatibilityCheck_Minor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 already includes the same functionality. 的本地化字符串。
        /// </summary>
        public static string CompatibilityCheck_SameFunctionality {
            get {
                return ResourceManager.GetString("CompatibilityCheck_SameFunctionality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use {0} instead. 的本地化字符串。
        /// </summary>
        public static string CompatibilityCheck_UseInstead {
            get {
                return ResourceManager.GetString("CompatibilityCheck_UseInstead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unsubscribe 的本地化字符串。
        /// </summary>
        public static string CompatibilityMessageBox_Unsubscribe {
            get {
                return ResourceManager.GetString("CompatibilityMessageBox_Unsubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Press any key 的本地化字符串。
        /// </summary>
        public static string KeyBinding_PressAnyKey {
            get {
                return ResourceManager.GetString("KeyBinding_PressAnyKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 German 的本地化字符串。
        /// </summary>
        public static string Language_de {
            get {
                return ResourceManager.GetString("Language_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English 的本地化字符串。
        /// </summary>
        public static string Language_en {
            get {
                return ResourceManager.GetString("Language_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Spanish 的本地化字符串。
        /// </summary>
        public static string Language_es_ES {
            get {
                return ResourceManager.GetString("Language_es_ES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 French 的本地化字符串。
        /// </summary>
        public static string Language_fr {
            get {
                return ResourceManager.GetString("Language_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game Language 的本地化字符串。
        /// </summary>
        public static string Language_GameLanguage {
            get {
                return ResourceManager.GetString("Language_GameLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Italian 的本地化字符串。
        /// </summary>
        public static string Language_it {
            get {
                return ResourceManager.GetString("Language_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Japanese 的本地化字符串。
        /// </summary>
        public static string Language_ja {
            get {
                return ResourceManager.GetString("Language_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Korean 的本地化字符串。
        /// </summary>
        public static string Language_ko {
            get {
                return ResourceManager.GetString("Language_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dutch 的本地化字符串。
        /// </summary>
        public static string Language_nl {
            get {
                return ResourceManager.GetString("Language_nl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Polish 的本地化字符串。
        /// </summary>
        public static string Language_pl {
            get {
                return ResourceManager.GetString("Language_pl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Portuguese 的本地化字符串。
        /// </summary>
        public static string Language_pt {
            get {
                return ResourceManager.GetString("Language_pt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Portuguese-Brazil 的本地化字符串。
        /// </summary>
        public static string Language_pt_BR {
            get {
                return ResourceManager.GetString("Language_pt_BR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Russian 的本地化字符串。
        /// </summary>
        public static string Language_ru {
            get {
                return ResourceManager.GetString("Language_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Turkish 的本地化字符串。
        /// </summary>
        public static string Language_tr {
            get {
                return ResourceManager.GetString("Language_tr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Simplified Chinese 的本地化字符串。
        /// </summary>
        public static string Language_zh_CN {
            get {
                return ResourceManager.GetString("Language_zh_CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Traditional Chinese 的本地化字符串。
        /// </summary>
        public static string Language_zh_TW {
            get {
                return ResourceManager.GetString("Language_zh_TW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Added 的本地化字符串。
        /// </summary>
        public static string LogMessageBox_Added {
            get {
                return ResourceManager.GetString("LogMessageBox_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Adjusted 的本地化字符串。
        /// </summary>
        public static string LogMessageBox_Adjusted {
            get {
                return ResourceManager.GetString("LogMessageBox_Adjusted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fixed 的本地化字符串。
        /// </summary>
        public static string LogMessageBox_Fixed {
            get {
                return ResourceManager.GetString("LogMessageBox_Fixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Optimized 的本地化字符串。
        /// </summary>
        public static string LogMessageBox_Optimized {
            get {
                return ResourceManager.GetString("LogMessageBox_Optimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Removed 的本地化字符串。
        /// </summary>
        public static string LogMessageBox_Removed {
            get {
                return ResourceManager.GetString("LogMessageBox_Removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Updated 的本地化字符串。
        /// </summary>
        public static string LogMessageBox_Updated {
            get {
                return ResourceManager.GetString("LogMessageBox_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Did not detect any incompatible mods. 的本地化字符串。
        /// </summary>
        public static string MessageBox_NormalPrompt {
            get {
                return ResourceManager.GetString("MessageBox_NormalPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        public static string MessageBox_OK {
            get {
                return ResourceManager.GetString("MessageBox_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Incompatible mods have been detected, in order to ensure this mod works properly, you need to unsubscribe following mods: 的本地化字符串。
        /// </summary>
        public static string MessageBox_WarningPrompt {
            get {
                return ResourceManager.GetString("MessageBox_WarningPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No 的本地化字符串。
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Advanced 的本地化字符串。
        /// </summary>
        public static string OptionPanel_Advanced {
            get {
                return ResourceManager.GetString("OptionPanel_Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Builtin Function 的本地化字符串。
        /// </summary>
        public static string OptionPanel_BuiltinFunction {
            get {
                return ResourceManager.GetString("OptionPanel_BuiltinFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compatibility Check 的本地化字符串。
        /// </summary>
        public static string OptionPanel_CompatibilityCheck {
            get {
                return ResourceManager.GetString("OptionPanel_CompatibilityCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Advanced functions. It is only used for debugging output. If something goes wrong, it is recommended to enable this option and send your log to developer after repeating issues. 的本地化字符串。
        /// </summary>
        public static string OptionPanel_DebugMinor {
            get {
                return ResourceManager.GetString("OptionPanel_DebugMinor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Debug mode 的本地化字符串。
        /// </summary>
        public static string OptionPanel_DebugMode {
            get {
                return ResourceManager.GetString("OptionPanel_DebugMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General 的本地化字符串。
        /// </summary>
        public static string OptionPanel_General {
            get {
                return ResourceManager.GetString("OptionPanel_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hotkeys 的本地化字符串。
        /// </summary>
        public static string OptionPanel_Hotkeys {
            get {
                return ResourceManager.GetString("OptionPanel_Hotkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is Disabled 的本地化字符串。
        /// </summary>
        public static string OptionPanel_IsDisabled {
            get {
                return ResourceManager.GetString("OptionPanel_IsDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is Enabled 的本地化字符串。
        /// </summary>
        public static string OptionPanel_IsEnabled {
            get {
                return ResourceManager.GetString("OptionPanel_IsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mod Information 的本地化字符串。
        /// </summary>
        public static string OptionPanel_ModInfo {
            get {
                return ResourceManager.GetString("OptionPanel_ModInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version 的本地化字符串。
        /// </summary>
        public static string OptionPanel_Version {
            get {
                return ResourceManager.GetString("OptionPanel_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scroll the wheel to change, Shift X10, Ctrl X0.1 的本地化字符串。
        /// </summary>
        public static string ScrollWheel {
            get {
                return ResourceManager.GetString("ScrollWheel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show control panel 的本地化字符串。
        /// </summary>
        public static string ShowControlPanel {
            get {
                return ResourceManager.GetString("ShowControlPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning! Mod cannot normally read the old configuration data. Now default configuration has been loaded for the mod. Please go to options panel and configure your Settings before starting game. 的本地化字符串。
        /// </summary>
        public static string XMLWariningMessageBox_Warning {
            get {
                return ResourceManager.GetString("XMLWariningMessageBox_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yes 的本地化字符串。
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
