// <auto-generated />
// This file was generated by a T4 template. Do not modify directly.

using CSLModsCommon.Manager;

namespace GameAnarchy.Localization;

public static class Translations {
    /// <summary>
    /// Enable/Disable All
    /// </summary>
    public static string EnableOrDisableAll => LocalizationManager.Localize("EnableOrDisableAll");

    /// <summary>
    /// Disable
    /// </summary>
    public static string Disable => LocalizationManager.Localize("Disable");

    /// <summary>
    /// Enable
    /// </summary>
    public static string Enable => LocalizationManager.Localize("Enable");

    /// <summary>
    /// Anarchy
    /// </summary>
    public static string Anarchy => LocalizationManager.Localize("Anarchy");

    /// <summary>
    /// Money Mode
    /// </summary>
    public static string MoneyMode => LocalizationManager.Localize("MoneyMode");

    /// <summary>
    /// Unlock Mode
    /// </summary>
    public static string UnlockMode => LocalizationManager.Localize("UnlockMode");

    /// <summary>
    /// Unlock All: If this option is not selected, some features may still be unlocked. Make sure you have disabled the [Unlock All] option in Find It! mod. Custom Unlock: Although custom unlock options take effect when the game refreshes milestones. Note: It is recommended to enable this before starting the game. The [Unlock All] option in Find It! mod only unlocks all assets in the Find It! menu, but does not unlock milestones.
    /// </summary>
    public static string UnlockModeDescription => LocalizationManager.Localize("UnlockModeDescription");

    /// <summary>
    /// Add money
    /// </summary>
    public static string AddMoney => LocalizationManager.Localize("AddMoney");

    /// <summary>
    /// Add money amount
    /// </summary>
    public static string AddMoneyAmount => LocalizationManager.Localize("AddMoneyAmount");

    /// <summary>
    /// Add money threshold
    /// </summary>
    public static string AddMoneyThreshold => LocalizationManager.Localize("AddMoneyThreshold");

    /// <summary>
    /// Make sure Money Anarchy feature is enabled
    /// </summary>
    public static string AddMoneyTooltip => LocalizationManager.Localize("AddMoneyTooltip");

    /// <summary>
    /// This option allows dynamic toggle within game
    /// </summary>
    public static string AllowsDynamicToggling => LocalizationManager.Localize("AllowsDynamicToggling");

    /// <summary>
    /// Amount
    /// </summary>
    public static string Amount => LocalizationManager.Localize("Amount");

    /// <summary>
    /// Annual interest rate
    /// </summary>
    public static string AnnualInterestRate => LocalizationManager.Localize("AnnualInterestRate");

    /// <summary>
    /// The default value is 3%
    /// </summary>
    public static string AnnualInterestRateMinor => LocalizationManager.Localize("AnnualInterestRateMinor");

    /// <summary>
    /// Building refund
    /// </summary>
    public static string BuildingRefund => LocalizationManager.Localize("BuildingRefund");

    /// <summary>
    /// Building refund multiple factor
    /// </summary>
    public static string BuildingRefundMultipleFactor => LocalizationManager.Localize("BuildingRefundMultipleFactor");

    /// <summary>
    /// Building spread fire probability
    /// </summary>
    public static string BuildingSpreadFireProbability => LocalizationManager.Localize("BuildingSpreadFireProbability");

    /// <summary>
    /// Charge interest on negative balances
    /// </summary>
    public static string ChargeInterest => LocalizationManager.Localize("ChargeInterest");

    /// <summary>
    /// City bankruptcy warning threshold
    /// </summary>
    public static string CityBankruptcyWarningThreshold => LocalizationManager.Localize("CityBankruptcyWarningThreshold");

    /// <summary>
    /// Game default value is -10000
    /// </summary>
    public static string CityBankruptcyWarningThresholdMinor => LocalizationManager.Localize("CityBankruptcyWarningThresholdMinor");

    /// <summary>
    /// City Service Options
    /// </summary>
    public static string CityServiceOptions => LocalizationManager.Localize("CityServiceOptions");

    /// <summary>
    /// Commercial
    /// </summary>
    public static string Commercial => LocalizationManager.Localize("Commercial");

    /// <summary>
    /// Cost
    /// </summary>
    public static string Cost => LocalizationManager.Localize("Cost");

    /// <summary>
    /// Custom unlock
    /// </summary>
    public static string CustomUnlock => LocalizationManager.Localize("CustomUnlock");

    /// <summary>
    /// Decrease Money
    /// </summary>
    public static string DecreaseMoney => LocalizationManager.Localize("DecreaseMoney");

    /// <summary>
    /// Economy
    /// </summary>
    public static string Economy => LocalizationManager.Localize("Economy");

    /// <summary>
    /// Achievements system is always available
    /// </summary>
    public static string EnableAchievements => LocalizationManager.Localize("EnableAchievements");

    /// <summary>
    /// Skip game Intro interface
    /// </summary>
    public static string EnabledSkipIntro => LocalizationManager.Localize("EnabledSkipIntro");

    /// <summary>
    /// Place unique buildings without limit
    /// </summary>
    public static string EnabledUnlimitedUniqueBuildings => LocalizationManager.Localize("EnabledUnlimitedUniqueBuildings");

    /// <summary>
    /// Fast Return
    /// </summary>
    public static string FastReturn => LocalizationManager.Localize("FastReturn");

    /// <summary>
    /// Festival area
    /// </summary>
    public static string FestivalArea => LocalizationManager.Localize("FestivalArea");

    /// <summary>
    /// Fire Control
    /// </summary>
    public static string FireControl => LocalizationManager.Localize("FireControl");

    /// <summary>
    /// Free
    /// </summary>
    public static string Free => LocalizationManager.Localize("Free");

    /// <summary>
    /// Ground pollution
    /// </summary>
    public static string GroundPollution => LocalizationManager.Localize("GroundPollution");

    /// <summary>
    /// Income multiplier
    /// </summary>
    public static string IncomeMultiplier => LocalizationManager.Localize("IncomeMultiplier");

    /// <summary>
    /// Industrial
    /// </summary>
    public static string Industrial => LocalizationManager.Localize("Industrial");

    /// <summary>
    /// Main campus building
    /// </summary>
    public static string MainCampusBuilding => LocalizationManager.Localize("MainCampusBuilding");

    /// <summary>
    /// Maximize attractiveness, will attract more tourists
    /// </summary>
    public static string MaximizeAttractiveness => LocalizationManager.Localize("MaximizeAttractiveness");

    /// <summary>
    /// Maximize education coverage, still need schools to get educated citizens
    /// </summary>
    public static string MaximizeEducationCoverage => LocalizationManager.Localize("MaximizeEducationCoverage");

    /// <summary>
    /// Maximize entertainment, will improve citizens' happiness
    /// </summary>
    public static string MaximizeEntertainment => LocalizationManager.Localize("MaximizeEntertainment");

    /// <summary>
    /// Maximize fire coverage
    /// </summary>
    public static string MaximizeFireCoverage => LocalizationManager.Localize("MaximizeFireCoverage");

    /// <summary>
    /// Maximize the land value of city
    /// </summary>
    public static string MaximizeLandValue => LocalizationManager.Localize("MaximizeLandValue");

    /// <summary>
    /// Big City
    /// </summary>
    public static string BigCity => LocalizationManager.Localize("BigCity");

    /// <summary>
    /// Big Town
    /// </summary>
    public static string BigTown => LocalizationManager.Localize("BigTown");

    /// <summary>
    /// Boom Town
    /// </summary>
    public static string BoomTown => LocalizationManager.Localize("BoomTown");

    /// <summary>
    /// Busy Town
    /// </summary>
    public static string BusyTown => LocalizationManager.Localize("BusyTown");

    /// <summary>
    /// Capital City
    /// </summary>
    public static string CapitalCity => LocalizationManager.Localize("CapitalCity");

    /// <summary>
    /// Colossal City
    /// </summary>
    public static string ColossalCity => LocalizationManager.Localize("ColossalCity");

    /// <summary>
    /// Grand City
    /// </summary>
    public static string GrandCity => LocalizationManager.Localize("GrandCity");

    /// <summary>
    /// Little Hamlet
    /// </summary>
    public static string LittleHamlet => LocalizationManager.Localize("LittleHamlet");

    /// <summary>
    /// Megalopolis
    /// </summary>
    public static string Megalopolis => LocalizationManager.Localize("Megalopolis");

    /// <summary>
    /// Metropolis
    /// </summary>
    public static string Metropolis => LocalizationManager.Localize("Metropolis");

    /// <summary>
    /// Milestone unlock level
    /// </summary>
    public static string MilestoneUnlockLevel => LocalizationManager.Localize("MilestoneUnlockLevel");

    /// <summary>
    /// Small City
    /// </summary>
    public static string SmallCity => LocalizationManager.Localize("SmallCity");

    /// <summary>
    /// Tiny Town
    /// </summary>
    public static string TinyTown => LocalizationManager.Localize("TinyTown");

    /// <summary>
    /// Vanilla
    /// </summary>
    public static string Vanilla => LocalizationManager.Localize("Vanilla");

    /// <summary>
    /// Worthy Village
    /// </summary>
    public static string WorthyVillage => LocalizationManager.Localize("WorthyVillage");

    /// <summary>
    /// Extends and optimize game's functions.
    /// </summary>
    public static string ModDescription => LocalizationManager.Localize("ModDescription");

    /// <summary>
    /// Monument
    /// </summary>
    public static string Monument => LocalizationManager.Localize("Monument");

    /// <summary>
    /// Noise pollution
    /// </summary>
    public static string NoisePollution => LocalizationManager.Localize("NoisePollution");

    /// <summary>
    /// No policies costs
    /// </summary>
    public static string NoPoliciesCosts => LocalizationManager.Localize("NoPoliciesCosts");

    /// <summary>
    /// Policies does not cost money.
    /// </summary>
    public static string NoPoliciesCostsMinor => LocalizationManager.Localize("NoPoliciesCostsMinor");

    /// <summary>
    /// Non-spread of fire
    /// </summary>
    public static string NoSpreadFire => LocalizationManager.Localize("NoSpreadFire");

    /// <summary>
    /// Office
    /// </summary>
    public static string Office => LocalizationManager.Localize("Office");

    /// <summary>
    /// Oil depletion rate
    /// </summary>
    public static string OilDepletionRate => LocalizationManager.Localize("OilDepletionRate");

    /// <summary>
    /// Optimize Options
    /// </summary>
    public static string OptimizeOptions => LocalizationManager.Localize("OptimizeOptions");

    /// <summary>
    /// This option takes effect after adjustment
    /// </summary>
    public static string OptionPanelCategoriesHorizontalOffsetMinor => LocalizationManager.Localize("OptionPanelCategoriesHorizontalOffsetMinor");

    /// <summary>
    /// Show mod updated date in options panel categories
    /// </summary>
    public static string OptionPanelCategoriesUpdated => LocalizationManager.Localize("OptionPanelCategoriesUpdated");

    /// <summary>
    /// This option only takes effect after refreshing the plugins list or restarting the game
    /// </summary>
    public static string OptionPanelCategoriesUpdatedMinor => LocalizationManager.Localize("OptionPanelCategoriesUpdatedMinor");

    /// <summary>
    /// Options panel categories bar horizontal offset
    /// </summary>
    public static string OptionsPanelHorizontalOffset => LocalizationManager.Localize("OptionsPanelHorizontalOffset");

    /// <summary>
    /// Ore depletion rate
    /// </summary>
    public static string OreDepletionRate => LocalizationManager.Localize("OreDepletionRate");

    /// <summary>
    /// Put out
    /// </summary>
    public static string PutOut => LocalizationManager.Localize("PutOut");

    /// <summary>
    /// Put out burning buildings
    /// </summary>
    public static string PutOutBurningBuildings => LocalizationManager.Localize("PutOutBurningBuildings");

    /// <summary>
    /// This is not a permanent fire removal feature and will only be called once to remove all buildings that are on fire. Are you sure you want to put out burning buildings?
    /// </summary>
    public static string PutOutBurningBuildingsDescription => LocalizationManager.Localize("PutOutBurningBuildingsDescription");

    /// <summary>
    /// Bulldozing refund
    /// </summary>
    public static string Refund => LocalizationManager.Localize("Refund");

    /// <summary>
    /// Relocate building
    /// </summary>
    public static string RelocateBuilding => LocalizationManager.Localize("RelocateBuilding");

    /// <summary>
    /// Construction cost * Multiplier factor = Cost
    /// </summary>
    public static string RelocateBuildingMinor => LocalizationManager.Localize("RelocateBuildingMinor");

    /// <summary>
    /// Remove airport building fire
    /// </summary>
    public static string RemoveAirportBuildingFire => LocalizationManager.Localize("RemoveAirportBuildingFire");

    /// <summary>
    /// Remove building refund time limitation
    /// </summary>
    public static string RemoveBuildingRefundTimeLimitation => LocalizationManager.Localize("RemoveBuildingRefundTimeLimitation");

    /// <summary>
    /// Remove campus building fire
    /// </summary>
    public static string RemoveCampusBuildingFire => LocalizationManager.Localize("RemoveCampusBuildingFire");

    /// <summary>
    /// Remove commercial building fire
    /// </summary>
    public static string RemoveCommercialBuildingFire => LocalizationManager.Localize("RemoveCommercialBuildingFire");

    /// <summary>
    /// Remove criminals from all buildings and maximize police service coverage
    /// </summary>
    public static string RemoveCrime => LocalizationManager.Localize("RemoveCrime");

    /// <summary>
    /// Remove dead citizens and maximize death care coverage
    /// </summary>
    public static string RemoveDeath => LocalizationManager.Localize("RemoveDeath");

    /// <summary>
    /// Remove garbage
    /// </summary>
    public static string RemoveGarbage => LocalizationManager.Localize("RemoveGarbage");

    /// <summary>
    /// Remove industrial building fire
    /// </summary>
    public static string RemoveIndustrialBuildingFire => LocalizationManager.Localize("RemoveIndustrialBuildingFire");

    /// <summary>
    /// Remove museum fire
    /// </summary>
    public static string RemoveMuseumFire => LocalizationManager.Localize("RemoveMuseumFire");

    /// <summary>
    /// Remove not enough money limitation
    /// </summary>
    public static string RemoveNotEnoughMoney => LocalizationManager.Localize("RemoveNotEnoughMoney");

    /// <summary>
    /// When Money Anarchy or Unlimited Money is enabled, this option is enabled automatically enforced.
    /// </summary>
    public static string RemoveNotEnoughMoneyMinor => LocalizationManager.Localize("RemoveNotEnoughMoneyMinor");

    /// <summary>
    /// Remove office building fire
    /// </summary>
    public static string RemoveOfficeBuildingFire => LocalizationManager.Localize("RemoveOfficeBuildingFire");

    /// <summary>
    /// Remove park building fire
    /// </summary>
    public static string RemoveParkBuildingFire => LocalizationManager.Localize("RemoveParkBuildingFire");

    /// <summary>
    /// Remove player building fire
    /// </summary>
    public static string RemovePlayerBuildingFire => LocalizationManager.Localize("RemovePlayerBuildingFire");

    /// <summary>
    /// Remove pollution
    /// </summary>
    public static string RemovePollution => LocalizationManager.Localize("RemovePollution");

    /// <summary>
    /// Remove residential building fire
    /// </summary>
    public static string RemoveResidentialBuildingFire => LocalizationManager.Localize("RemoveResidentialBuildingFire");

    /// <summary>
    /// Remove Segment refund time limitation
    /// </summary>
    public static string RemoveSegmentRefundTimeLimitation => LocalizationManager.Localize("RemoveSegmentRefundTimeLimitation");

    /// <summary>
    /// Residential
    /// </summary>
    public static string Residential => LocalizationManager.Localize("Residential");

    /// <summary>
    /// Resource Options
    /// </summary>
    public static string ResourceOptions => LocalizationManager.Localize("ResourceOptions");

    /// <summary>
    /// Segment refund
    /// </summary>
    public static string SegmentRefund => LocalizationManager.Localize("SegmentRefund");

    /// <summary>
    /// Segment refund multiple factor
    /// </summary>
    public static string SegmentRefundMultipleFactor => LocalizationManager.Localize("SegmentRefundMultipleFactor");

    /// <summary>
    /// Service
    /// </summary>
    public static string Service => LocalizationManager.Localize("Service");

    /// <summary>
    /// Sort mods names in options panel
    /// </summary>
    public static string SortSettings => LocalizationManager.Localize("SortSettings");

    /// <summary>
    /// Space radar
    /// </summary>
    public static string SpaceRadar => LocalizationManager.Localize("SpaceRadar");

    /// <summary>
    /// Game start money
    /// </summary>
    public static string StartMoneyMajor => LocalizationManager.Localize("StartMoneyMajor");

    /// <summary>
    /// Set value before you start gaming. If you don't want money to be this value every time you load save, disable this feature after enabling it once, if you load save, the money will change after the game simulation starts.
    /// </summary>
    public static string StartMoneyMinor => LocalizationManager.Localize("StartMoneyMinor");

    /// <summary>
    /// Stock exchange
    /// </summary>
    public static string StockExchange => LocalizationManager.Localize("StockExchange");

    /// <summary>
    /// Tree spread fire probability
    /// </summary>
    public static string TreeSpreadFireProbability => LocalizationManager.Localize("TreeSpreadFireProbability");

    /// <summary>
    /// Unique factory
    /// </summary>
    public static string UniqueFactory => LocalizationManager.Localize("UniqueFactory");

    /// <summary>
    /// Unique faculty
    /// </summary>
    public static string UniqueFaculty => LocalizationManager.Localize("UniqueFaculty");

    /// <summary>
    /// Unlimited
    /// </summary>
    public static string Unlimited => LocalizationManager.Localize("Unlimited");

    /// <summary>
    /// Library
    /// </summary>
    public static string UnlimitedLibraryAI => LocalizationManager.Localize("UnlimitedLibraryAI");

    /// <summary>
    /// The Creator's Library
    /// </summary>
    public static string UnlimitedLibraryAIMinor => LocalizationManager.Localize("UnlimitedLibraryAIMinor");

    /// <summary>
    /// Game Anarchy also extended money anarchy function, allowing manual add money, automatic add money, check Game Anarchy option panel.
    /// </summary>
    public static string UnlimitedMoneyConflict => LocalizationManager.Localize("UnlimitedMoneyConflict");

    /// <summary>
    /// Game Anarchy also can adjuster consumption rate, check Game Anarchy control panel in game.
    /// </summary>
    public static string UnlimitedOilAndOreConflict => LocalizationManager.Localize("UnlimitedOilAndOreConflict");

    /// <summary>
    /// Park
    /// </summary>
    public static string UnlimitedParkAI => LocalizationManager.Localize("UnlimitedParkAI");

    /// <summary>
    /// Plaza of the Future
    /// </summary>
    public static string UnlimitedParkAIMinor => LocalizationManager.Localize("UnlimitedParkAIMinor");

    /// <summary>
    /// Space elevator
    /// </summary>
    public static string UnlimitedSpaceElevator => LocalizationManager.Localize("UnlimitedSpaceElevator");

    /// <summary>
    /// Plaza of Transference
    /// </summary>
    public static string UnlimitedSpaceElevatorMinor => LocalizationManager.Localize("UnlimitedSpaceElevatorMinor");

    /// <summary>
    /// Unlock all
    /// </summary>
    public static string UnlockAll => LocalizationManager.Localize("UnlockAll");

    /// <summary>
    /// Game Anarchy also extend the custom unlock, check Game Anarchy option panel.
    /// </summary>
    public static string UnlockAllConflict => LocalizationManager.Localize("UnlockAllConflict");

    /// <summary>
    /// Unlock all roads
    /// </summary>
    public static string UnlockAllRoads => LocalizationManager.Localize("UnlockAllRoads");

    /// <summary>
    /// Unlock some basic roads, including some multi-lane roads
    /// </summary>
    public static string UnlockBasicRoadsMinor => LocalizationManager.Localize("UnlockBasicRoadsMinor");

    /// <summary>
    /// Unlock info views panel
    /// </summary>
    public static string UnlockInfoViews => LocalizationManager.Localize("UnlockInfoViews");

    /// <summary>
    /// Unlock landscaping
    /// </summary>
    public static string UnlockLandscaping => LocalizationManager.Localize("UnlockLandscaping");

    /// <summary>
    /// Unlock metro track
    /// </summary>
    public static string UnlockMetroTrack => LocalizationManager.Localize("UnlockMetroTrack");

    /// <summary>
    /// Unlock Options
    /// </summary>
    public static string UnlockOptions => LocalizationManager.Localize("UnlockOptions");

    /// <summary>
    /// Unlock policies panel
    /// </summary>
    public static string UnlockPolicies => LocalizationManager.Localize("UnlockPolicies");

    /// <summary>
    /// Unlock public transport
    /// </summary>
    public static string UnlockPublicTransport => LocalizationManager.Localize("UnlockPublicTransport");

    /// <summary>
    /// Unlock train track
    /// </summary>
    public static string UnlockTrainTrack => LocalizationManager.Localize("UnlockTrainTrack");

    /// <summary>
    /// Unlock all unique buildings at levels 1 through 6. Due to game restrictions, if this option is forced to be unlocked, a small number of buildings will be unlocked, but not all.
    /// </summary>
    public static string UnlockUniqueBuildingMinor => LocalizationManager.Localize("UnlockUniqueBuildingMinor");

    /// <summary>
    /// {0} days ago
    /// </summary>
    public static string Updated_DaysAgo(object arg0) => LocalizationManager.LocalizeFormat("Updated_DaysAgo", arg0);

    /// <summary>
    /// Last year
    /// </summary>
    public static string Updated_LastYear => LocalizationManager.Localize("Updated_LastYear");

    /// <summary>
    /// {0} month ago
    /// </summary>
    public static string Updated_MonthAgo(object arg0) => LocalizationManager.LocalizeFormat("Updated_MonthAgo", arg0);

    /// <summary>
    /// {0} months ago
    /// </summary>
    public static string Updated_MonthsAgo(object arg0) => LocalizationManager.LocalizeFormat("Updated_MonthsAgo", arg0);

    /// <summary>
    /// Today at {0:HH:mm}
    /// </summary>
    public static string Updated_Today(object arg0) => LocalizationManager.LocalizeFormat("Updated_Today", arg0);

    /// <summary>
    /// {0} years ago
    /// </summary>
    public static string Updated_YearsAgo(object arg0) => LocalizationManager.LocalizeFormat("Updated_YearsAgo", arg0);

    /// <summary>
    /// Yesterday
    /// </summary>
    public static string Updated_Yesterday => LocalizationManager.Localize("Updated_Yesterday");

    /// <summary>
    /// Yesterday at {0:HH:mm}
    /// </summary>
    public static string Updated_YesterdayAt(object arg0) => LocalizationManager.LocalizeFormat("Updated_YesterdayAt", arg0);

    /// <summary>
    /// {0} mod(s) active
    /// </summary>
    public static string ModsActive(object arg0) => LocalizationManager.LocalizeFormat("ModsActive", arg0);

    /// <summary>
    /// The achievement system has been forcibly enabled
    /// </summary>
    public static string AchievementForciblyEnabled => LocalizationManager.Localize("AchievementForciblyEnabled");

    /// <summary>
    /// Water pollution
    /// </summary>
    public static string WaterPollution => LocalizationManager.Localize("WaterPollution");

    /// <summary>
    /// Weather radar
    /// </summary>
    public static string WeatherRadar => LocalizationManager.Localize("WeatherRadar");

    /// <summary>
    /// Added unlimited placement of festival area buildings.
    /// </summary>
    public static string Changelog_v1_0_0_Added => LocalizationManager.Localize("Changelog_v1_0_0_Added");

    /// <summary>
    /// Fixed control panel settings sometimes not automatically save.
    /// </summary>
    public static string Changelog_v1_0_0_Fixed => LocalizationManager.Localize("Changelog_v1_0_0_Fixed");

    /// <summary>
    /// Updated to support game version 1.17.0
    /// </summary>
    public static string Changelog_v1_0_0_Updated => LocalizationManager.Localize("Changelog_v1_0_0_Updated");

    /// <summary>
    /// Fixed an issue where normal buildings could only be placed once.
    /// </summary>
    public static string Changelog_v1_0_1_Fixed => LocalizationManager.Localize("Changelog_v1_0_1_Fixed");

    /// <summary>
    /// Fixed an issue where the mod would not work at all when loading the config file incorrectly.
    /// </summary>
    public static string Changelog_v1_0_1_Fixed1 => LocalizationManager.Localize("Changelog_v1_0_1_Fixed1");

    /// <summary>
    /// Added unlock landscaping feature.
    /// </summary>
    public static string Changelog_v1_1_0_Added => LocalizationManager.Localize("Changelog_v1_1_0_Added");

    /// <summary>
    /// Added put out burning buildings feature.
    /// </summary>
    public static string Changelog_v1_1_0_Added1 => LocalizationManager.Localize("Changelog_v1_1_0_Added1");

    /// <summary>
    /// Added unlimited place treasure hunt buildings feature.
    /// </summary>
    public static string Changelog_v1_1_0_Added2 => LocalizationManager.Localize("Changelog_v1_1_0_Added2");

    /// <summary>
    /// Integrated [You Can Build It] mod functions.
    /// </summary>
    public static string Changelog_v1_1_0_Added3 => LocalizationManager.Localize("Changelog_v1_1_0_Added3");

    /// <summary>
    /// Fixed an issue where unlock public transport was not fully unlocked.
    /// </summary>
    public static string Changelog_v1_1_0_Fixed => LocalizationManager.Localize("Changelog_v1_1_0_Fixed");

    /// <summary>
    /// Fixed an issue where unlimited oil, unlimited ore is not working properly.
    /// </summary>
    public static string Changelog_v1_1_0_Fixed1 => LocalizationManager.Localize("Changelog_v1_1_0_Fixed1");

    /// <summary>
    /// Optimize unlock info view performance issues.
    /// </summary>
    public static string Changelog_v1_1_0_Optimized => LocalizationManager.Localize("Changelog_v1_1_0_Optimized");

    /// <summary>
    /// Thai localization support
    /// </summary>
    public static string Changelog_v1_1_0_Translation => LocalizationManager.Localize("Changelog_v1_1_0_Translation");

    /// <summary>
    /// UUI button and separate tool button are now optional.
    /// </summary>
    public static string Changelog_v1_1_0_Updated => LocalizationManager.Localize("Changelog_v1_1_0_Updated");

    /// <summary>
    /// Updated to support game version 1.17.1
    /// </summary>
    public static string Changelog_v1_1_0_Updated1 => LocalizationManager.Localize("Changelog_v1_1_0_Updated1");

    /// <summary>
    /// Updated compatibility check. When three built-in unlimited mods are detected to be enabled, they are automatically disabled to ensure mod compatibility.
    /// </summary>
    public static string Changelog_v1_1_0_Updated2 => LocalizationManager.Localize("Changelog_v1_1_0_Updated2");

    /// <summary>
    /// Fixed an issue where the remove not enough money limitation function could not take effect.
    /// </summary>
    public static string Changelog_v1_1_1_Fixed => LocalizationManager.Localize("Changelog_v1_1_1_Fixed");

    /// <summary>
    /// Fixed some issues with the control panel.
    /// </summary>
    public static string Changelog_v1_1_1_Fixed1 => LocalizationManager.Localize("Changelog_v1_1_1_Fixed1");

    /// <summary>
    /// Fixed an issue where achievements didn't work properly.
    /// </summary>
    public static string Changelog_v1_1_2_Fixed => LocalizationManager.Localize("Changelog_v1_1_2_Fixed");

    /// <summary>
    /// Updated localization.
    /// </summary>
    public static string Changelog_v1_1_2_Updated => LocalizationManager.Localize("Changelog_v1_1_2_Updated");

    /// <summary>
    /// Added custom unlock - Basic Road.
    /// </summary>
    public static string Changelog_v1_1_3_Added => LocalizationManager.Localize("Changelog_v1_1_3_Added");

    /// <summary>
    /// Optimize some functions.
    /// </summary>
    public static string Changelog_v1_1_3_Optimized => LocalizationManager.Localize("Changelog_v1_1_3_Optimized");

    /// <summary>
    /// Updated CitiesHarmony to 2.2
    /// </summary>
    public static string Changelog_v1_1_3_Updated => LocalizationManager.Localize("Changelog_v1_1_3_Updated");

    /// <summary>
    /// Added decrease money function.
    /// </summary>
    public static string Changelog_v1_1_4_Added => LocalizationManager.Localize("Changelog_v1_1_4_Added");

    /// <summary>
    /// Integrate No Policy Costs functionality.
    /// </summary>
    public static string Changelog_v1_1_4_Added1 => LocalizationManager.Localize("Changelog_v1_1_4_Added1");

    /// <summary>
    /// Fixed an issue where the fire station would not send out vehicles after remove fire was enabled.
    /// </summary>
    public static string Changelog_v1_1_4_Fixed => LocalizationManager.Localize("Changelog_v1_1_4_Fixed");

    /// <summary>
    /// Updated to CSShared framework.
    /// </summary>
    public static string Changelog_v1_2_0_Updated => LocalizationManager.Localize("Changelog_v1_2_0_Updated");

    /// <summary>
    /// Updated localization.
    /// </summary>
    public static string Changelog_v1_2_1_Updated => LocalizationManager.Localize("Changelog_v1_2_1_Updated");

    /// <summary>
    /// Fixed serialization exception issues.
    /// </summary>
    public static string Changelog_v1_2_1_Fixed => LocalizationManager.Localize("Changelog_v1_2_1_Fixed");

    /// <summary>
    /// Added achievements system enabled prompt.
    /// </summary>
    public static string Changelog_v1_3_0_Added => LocalizationManager.Localize("Changelog_v1_3_0_Added");

    /// <summary>
    /// Fixed exception thrown when toggling achievement system before game.
    /// </summary>
    public static string Changelog_v1_3_0_Fixed => LocalizationManager.Localize("Changelog_v1_3_0_Fixed");

    /// <summary>
    /// This update automatically resets all settings.
    /// </summary>
    public static string Changelog_v1_3_0_Attention => LocalizationManager.Localize("Changelog_v1_3_0_Attention");

}
